services:
  asesorias-microservice:
    container_name: asesorias-microservice
    image: asesorias-microservice:v1
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - asesorias-network

  asesorias-microservice-2:
    container_name: asesorias-microservice-2
    image: asesorias-microservice:v1
    ports:
      - "3002:3001"
    networks:
      - asesorias-network

  load-balancer:
    container_name: load-balancer
    image: load-balancer:v1
    build:
      context: ./balancer
    ports:
      - "5000:80"
    networks:
      - asesorias-network

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-nodejs
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  asesorias-network: